######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 27 09:35:57 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
